from datetime import date
from marshmallow import Schema, fields, pprint

class GEOEntity(Schema):
    geo_accession = fields.List(fields.String())
    title         = fields.String()
    status        = fields.String()
    submission_date = fields.DateTime()
    last_update_date = fields.DateTime()
    summary       = fields.String()
    overall_design = fields.String(allow_none = True)
    types          = fields.List(fields.String())
    contributors   = fields.List(fields.String())
    sample_id      = fields.List(fields.String())
    contact_name   = fields.String()
    contact_department = fields.String()
    contact_institute = fields.String()
    contact_address = fields.String()
    contact_city = fields.String()
    contact_state = fields.String()
    contact_postal_code = fields.String()
    contact_country = fields.String()
    platform_id     = fields.List(fields.String())
    platform_organism = fields.List(fields.String())
    platform_taxid   = fields.List(fields.Int())
    sample_taxid   = fields.List(fields.Int())
    sample_id = fields.List(fields.String())
    sample_organism = fields.List(fields.String())
    relation  = fields.List(fields.String())
    bioprojects = fields.List(fields.String())
    subseries = fields.List(fields.String())
    sra_studies = fields.List(fields.String())
    published_date = fields.DateTime()
