# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='omicidx',
    version='0.2.0',
    description='Hello there',
    python_requires='==3.*,>=3.7.0',
    author='Sean Davis',
    author_email='seandavi@gmail.com',
    license='MIT',
    packages=[
        'omicidx', 'omicidx.model', 'omicidx.schema', 'omicidx.scripts',
        'omicidx.sra'
    ],
    package_data={
        'omicidx.schema': ['*.schema'],
        'omicidx': [
            '*.py~', 'data/*.json', 'data/*.json~', 'processing/*.py~',
            'pydantic/*.py~'
        ],
        'omicidx.sra': ['*.py~']
    },
    install_requires=[
        'boto3==1.*,>=1.9.0', 'pydantic==0.*,>=0.30.0',
        'requests==2.*,>=2.22.0', 'click'
    ],
    extras_require={
        'dev': [
            'jupyter==1.*,>=1.0.0', 'jupyterlab==1.*,>=1.0.0',
            'psycopg2==2.*,>=2.8.0'
        ]
    },
)
