baseurl = "https://seandavi.github.io/"
languageCode = "en-us"
title = "The Omix Metadata Index Project"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = "UA-93043521-1"

# SD: added to allow hugo to ignore blogdown stuff:
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
	# General information
	author = "Sean Davis"
	description = "We build and maintain a set of metadata resources related to high throughput data resources. "
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/seandavi/omicidx"

	version = "0.1.0"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = "zenburn"

	[params.palette]
    	primary = "blue"
    	accent  = "teal"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = "seandavis12"
	github  = "seandavi"
	email   = "seandavi@gmail.com"


[[menu.main]]
	name   = "About"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "Getting started"
	url    = "getting-started/"
	weight = 10

[[menu.main]]
	name   = "Roadmap"
	url    = "roadmap/"
	weight = 30

[[menu.main]]
	name   = "Technical Docs"
	url    = "technical-docs/"
	weight = 40


[[menu.main]]
	name   = "License"
	url    = "license/"
	weight = 40


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
